default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= File.join(Dir.pwd, '../tmp/sockets') %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: course

test:
  <<: *default
  database: course_test
